name: Build LaTeX Document

on:
  push:
    branches: [ "2.0", "master" ]
  pull_request:
    branches: [ "2.0", "master" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: 2.0.tex
          latexmk_use_xelatex: true  
          args: "-interaction=nonstopmode -file-line-error"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4  
        with:
          name: Paper-PDF
          path: 2.0.pdf
